name: Release App Workflow

on:
  release:
    types: [ published ]
  schedule:
    - cron: '0 6 * * *'

jobs:
  npm-install-dependencies:
    uses: krajvy/html2rss/.github/workflows/npm_install.yml@main

  build-app:
    runs-on: ubuntu-latest

    needs:
      - npm-install-dependencies

    steps:
      - uses: actions/checkout@v4

      - name: Use Node.js 20
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Get directories paths
        id: dirs
        run: |
          echo "npm-cache-dir=$(npm config get cache)" >> $GITHUB_OUTPUT
          echo "node-modules-dir=**/node_modules" >> $GITHUB_OUTPUT

      - name: Cache NPM packages
        uses: actions/cache@v4
        id: npm-cache # use this to check for `cache-hit` ==> if: steps.npm-cache.outputs.cache-hit != 'true'
        with:
          path: |
            ${{ steps.dirs.outputs.npm-cache-dir }}
            ${{ steps.dirs.outputs.node-modules-dir }}
          key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

      - name: Throw an error when NPM is not ready
        if: ${{ steps.npm-cache.outputs.cache-hit != 'true' }}
        run: exit 1

      - name: Build App
        run: npm run build

      - name: Generate RSS Feeds
        run: npm run generate

      - name: Deploy to branch gh-pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: build
